apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ct-engine-staging

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "staging"
    target:
      kind: Deployment
      name: ct-execution
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "staging"
    target:
      kind: Deployment
      name: ct-manager
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "staging"
    target:
      kind: Deployment
      name: ct-monitor

images:
  - name: your-registry/ct-engine
    newTag: staging-latest

replicas:
  - name: ct-execution
    count: 2
  - name: ct-manager
    count: 1
